from bs4 import BeautifulSoup
with open("website.html") as file:
    data = file.read()
soup = BeautifulSoup(data,'html.parser')
# print(soup.prettify())
# print(soup.a)
# print(soup.title)
# print(soup.title.name)
# print(soup.title.string)
#  print(soup.find_all('a'))
# print(soup.find_all('p'))
# print(soup.get_text())
# print(soup.a['href'])
# print(soup.a.attrs)
# print(soup.a.get('href'))
# print(soup.find(name='a',href='https://www.appbrewery.co/'))
# print(soup.find(name='',class_=''))
# print(soup.select_one(selector="p a"))
# print(soup.select_one(selector="#name"))
# print(soup.select_one(selector=".heading"))
